spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB??useSSL=false&allowPublicKeyRetrieval=true&maxReconnects=3&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

